### ISSUE TITLE
不能用呀

### ISSUE THREAD

**Issue by kinorsi** [zhouzhongyuan/cordova-plugin-geoloaction-baidu-android#2]
兄弟~我这边试了好几次老是用不了。
提示baidu_location不在在~

**Comment by zhouzhongyuan** [comment]
你的cordova 版本是什么？
在模拟器中调试的 还是在真机上调试的？

**Comment by zhouzhongyuan** [comment]
经过我这边尝试，你应该是在deviceReady之前调用了baidu_location。
所有的插件相关的函数 只有在deviceReady之后才能调用。

**Comment by kinorsi** [comment]
我靠。。你是对的。。真是不好意思呀！ 多谢了~~
另外定位sdk已经更新到V6.1.3了~~有空更新下呗~

**Comment by kinorsi** [comment]
还有个问题。。那个watchPosition这样的方法没有的？
你的另外一个工程cordova-plugin-geolocation-baidu这个怎么和cordova-plugin-geolocation是一样的？是不是还没有改啊？

**Comment by zhouzhongyuan** [comment]
@kinorsi 暂时只支持getPositon；
最近就会升级6.1.3.
是一样得，因为我还没有修改。
